### PR TITLE
Authenticate requests when env vars present

### PR DESCRIPTION
**Pull request by esimons**
With regards to #40

### CODE REVIEW

**Comment by esimons** [comment]
@Maciek416 @archlichking wondering if we could get a set of eyes on this PR as it's a pressing concern for our group, with builds breaking due to Sauce Labs rate-limiting. Thank you! Sorry for prodding and appreciate your time.

**Comment by archlichking** [comment]
💯 Thanks for the PR.

**Comment by archlichking** [comment]
@esimons this repo deprecated. Since `magellan@10` we use [magellan-saucelabs-executor](https://github.com/TestArmada/magellan-saucelabs-executor). Can you also do a PR to it if you're using it?

**Comment by esimons** [comment]
@archlichking thanks for the merge!
I don't think there's anything to change in saucelabs-executor, since it delegates to Guacamole for making calls to the Sauce Labs REST API:
https://github.com/TestArmada/magellan-saucelabs-executor/blob/10002ddf81b83fabb3e2483d43e0a64d3c945246/src/profile.js#L5
That being the case, even if this repo is planned to be deprecated, I think we'll need a new release of Guacamole to be published in the meantime.

**Comment by esimons** [comment]
@archlichking I don't see that a new version of this lib has been published, would it be possible to get this change published soon?

**Pull request merged**
